--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/andresbytes/EasyUI..
build-by-default: true
branches:
- pm4
- pm5
projects:
  libEasyUI:
    path: ""
    model: virion
    type: library
...
